version: '3.7'

services:
    db:
        image: postgres:latest
        ports:
            - 5432:5432
        restart: always
        environment:
            POSTGRES_PASSWORD: ads123
            POSTGRES_USER: tcss460
            POSTGRES_DB: tcss460
        container_name: lecture-db
        volumes:
            - ~/apps/postgres:/var/lib/postgresql/data
            - ./data/cleaned_books_v2.csv:/docker-entrypoint-initdb.d/cleaned_books_v2.csv
            - ./data/books-table-setup.sql:/docker-entrypoint-initdb.d/books-table-setup.sql
